// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package main

// Apikey defines model for Apikey.
type Apikey struct {
	Id Id `json:"id"`
}

// Apikeys defines model for Apikeys.
type Apikeys struct {
	Items []Apikey `json:"items"`
}

// DumpData defines model for DumpData.
type DumpData struct {
	Apikeys   *Apikeys   `json:"apikeys,omitempty"`
	Pets      *Pets      `json:"pets,omitempty"`
	Petstores *Petstores `json:"petstores,omitempty"`
	Sessions  *Sessions  `json:"sessions,omitempty"`
	Users     *Users     `json:"users,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Id defines model for Id.
type Id string

// LoginData defines model for LoginData.
type LoginData struct {
	Password string   `json:"password"`
	User     Username `json:"user"`
}

// NewPet defines model for NewPet.
type NewPet struct {
	Age        *int    `json:"age,omitempty"`
	Name       PetName `json:"name"`
	PetstoreId *Id     `json:"petstoreId,omitempty"`
}

// NewPetstore defines model for NewPetstore.
type NewPetstore struct {
	Name PetstoreName `json:"name"`
}

// Pet defines model for Pet.
type Pet struct {
	// Embedded struct due to allOf(#/components/schemas/NewPet)
	NewPet `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Id Id `json:"id"`
	// Embedded fields due to inline allOf schema
	Owner Username `json:"owner"`
}

// PetName defines model for PetName.
type PetName string

// Pets defines model for Pets.
type Pets struct {
	Items []Pet `json:"items"`
}

// Petstore defines model for Petstore.
type Petstore struct {
	// Embedded struct due to allOf(#/components/schemas/NewPetstore)
	NewPetstore `yaml:",inline"`
	// Embedded fields due to inline allOf schema
	Id Id `json:"id"`
}

// PetstoreName defines model for PetstoreName.
type PetstoreName string

// Petstores defines model for Petstores.
type Petstores struct {
	Items []Petstore `json:"items"`
}

// Session defines model for Session.
type Session struct {
	Id Id `json:"id"`
}

// Sessions defines model for Sessions.
type Sessions struct {
	Items []Session `json:"items"`
}

// User defines model for User.
type User struct {
	IsAdmin  bool     `json:"isAdmin"`
	Password string   `json:"password"`
	User     Username `json:"user"`
}

// Username defines model for Username.
type Username string

// Users defines model for Users.
type Users struct {
	Items []User `json:"items"`
}

// Version defines model for Version.
type Version struct {
	CommitId string `json:"commitId"`
	Version  string `json:"version"`
}

// PathId defines model for PathId.
type PathId Id

// PathUsername defines model for PathUsername.
type PathUsername Username

// N400 defines model for 400.
type N400 struct {
	Message string `json:"message"`
}

// N401 defines model for 401.
type N401 Error

// Default defines model for default.
type Default Error

// UserLoginJSONBody defines parameters for UserLogin.
type UserLoginJSONBody LoginData

// CreatePetJSONBody defines parameters for CreatePet.
type CreatePetJSONBody NewPet

// TransferPetJSONBody defines parameters for TransferPet.
type TransferPetJSONBody struct {
	PetstoreId Id `json:"petstoreId"`
}

// FindPetstoresParams defines parameters for FindPetstores.
type FindPetstoresParams struct {
	// name to filter by
	Name *PetstoreName `json:"name,omitempty"`

	// maximum number of results to return
	Limit *int32 `json:"limit,omitempty"`
}

// CreatePetstoreJSONBody defines parameters for CreatePetstore.
type CreatePetstoreJSONBody NewPetstore

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody User

// UserLoginJSONRequestBody defines body for UserLogin for application/json ContentType.
type UserLoginJSONRequestBody UserLoginJSONBody

// CreatePetJSONRequestBody defines body for CreatePet for application/json ContentType.
type CreatePetJSONRequestBody CreatePetJSONBody

// TransferPetJSONRequestBody defines body for TransferPet for application/json ContentType.
type TransferPetJSONRequestBody TransferPetJSONBody

// CreatePetstoreJSONRequestBody defines body for CreatePetstore for application/json ContentType.
type CreatePetstoreJSONRequestBody CreatePetstoreJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody
